
// VisualAidGenerator.ts
'use server';

/**
 * @fileOverview Generates blackboard-friendly sketches from text prompts.
 *
 * - generateVisualAid - A function that generates a visual aid.
 * - GenerateVisualAidInput - The input type for the generateVisualAid function.
 * - GenerateVisualAidOutput - The return type for the generateVisualAid function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateVisualAidInputSchema = z.object({
  prompt: z.string().describe('A text prompt describing the item to draw, e.g., \'A simple house\'.'),
});
export type GenerateVisualAidInput = z.infer<typeof GenerateVisualAidInputSchema>;

const GenerateVisualAidOutputSchema = z.object({
  mediaUrl: z.string().describe('The data URI of the generated sketch image.'),
});
export type GenerateVisualAidOutput = z.infer<typeof GenerateVisualAidOutputSchema>;

export async function generateVisualAid(input: GenerateVisualAidInput): Promise<GenerateVisualAidOutput> {
  return generateVisualAidFlow(input);
}

const generateVisualAidFlow = ai.defineFlow(
  {
    name: 'generateVisualAidFlow',
    inputSchema: GenerateVisualAidInputSchema,
    outputSchema: GenerateVisualAidOutputSchema,
  },
  async input => {
    // A more detailed prompt for better educational images.
    const sketchPrompt = `You are an expert science educator and diagram illustrator. Your task is to create a simple, clear, and scientifically accurate diagram for a classroom setting. The diagram should be easy for a child to understand.

    Subject: Create a diagram of '${input.prompt}'.

    Instructions:
    1.  **Accuracy is the top priority.** The diagram must correctly represent the scientific concept.
    2.  **Simplicity is key.** Use simple shapes and clear labels. Avoid unnecessary clutter.
    3.  **Educational Style:** The style should be like a clear, modern textbook illustration or a simple blackboard sketch.
    4.  **No Text in the Image:** Do not write any words, titles, or labels directly on the image itself. The diagram should be purely visual.
    
    Example: If the prompt is "the water cycle," you should draw a simple landscape with the sun, clouds, water evaporating from a lake, condensation into clouds, and precipitation (rain).`;
    
    try {
      const {media} = await ai.generate({
        model: 'googleai/gemini-2.0-flash-preview-image-generation',
        prompt: sketchPrompt,
        config: {
          responseModalities: ['TEXT', 'IMAGE'],
        },
      });

      if (!media?.url) {
        throw new Error('No image was generated by the model.');
      }

      return {
        mediaUrl: media.url,
      };
    } catch (error) {
      console.error('Visual aid generation failed:', error);
      if (
        error instanceof Error &&
        (error.message.includes('503') || error.message.includes('overloaded'))
      ) {
        throw new Error(
          'The AI model for images is currently busy. Please try again in a moment.'
        );
      }
      throw new Error(
        'An unexpected error occurred while generating the visual aid. Please try again.'
      );
    }
  }
);
